name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --all --verbose
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run rustfmt and check there's no difference
      run: cargo fmt --all -- --check
